// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-4ILfzCkqK2xqaAlXrWHV4MlP0mg2Sw',
    appId: '1:833357101402:web:5acdc78dace8b17fa71b63',
    messagingSenderId: '833357101402',
    projectId: 'whac-a-mole-game',
    authDomain: 'whac-a-mole-game.firebaseapp.com',
    databaseURL: 'https://whac-a-mole-game-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whac-a-mole-game.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEO2CkSOXYf-k58FyfYKv63pQdUUoIVoQ',
    appId: '1:833357101402:android:f2a082feeea5439aa71b63',
    messagingSenderId: '833357101402',
    projectId: 'whac-a-mole-game',
    databaseURL: 'https://whac-a-mole-game-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whac-a-mole-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-FZOfQPIk1r_20_n2rebV8HT89beC2KM',
    appId: '1:833357101402:ios:bfc4bf2b3bdd588da71b63',
    messagingSenderId: '833357101402',
    projectId: 'whac-a-mole-game',
    databaseURL: 'https://whac-a-mole-game-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whac-a-mole-game.firebasestorage.app',
    iosBundleId: 'com.example.whacAMoleGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-FZOfQPIk1r_20_n2rebV8HT89beC2KM',
    appId: '1:833357101402:ios:bfc4bf2b3bdd588da71b63',
    messagingSenderId: '833357101402',
    projectId: 'whac-a-mole-game',
    databaseURL: 'https://whac-a-mole-game-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whac-a-mole-game.firebasestorage.app',
    iosBundleId: 'com.example.whacAMoleGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS-4ILfzCkqK2xqaAlXrWHV4MlP0mg2Sw',
    appId: '1:833357101402:web:a24cfe8a668347d6a71b63',
    messagingSenderId: '833357101402',
    projectId: 'whac-a-mole-game',
    authDomain: 'whac-a-mole-game.firebaseapp.com',
    databaseURL: 'https://whac-a-mole-game-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whac-a-mole-game.firebasestorage.app',
  );
}
